### ISSUE TITLE
Not compatible with browserify

### ISSUE THREAD

**Issue by kumavis** [dchest/tweetnacl-util-js#9]
`browserify` builds will normally inject a `Buffer` polyfill, however this is disabled in this package's configuration.

https://github.com/dchest/tweetnacl-util-js/blob/7be17e460bfb96660c9d7b55f6a7ba1cc5f58dc9/package.json#L34

The result is a bundle that errors due to `require('buffer')` returning an empty object.

**Comment by dchest** [comment]
Hm, in what environment do you have these errors? Browserify is strange, why would it inject `require('buffer')`? Do you know how to avoid it instead of injecting? We don't use `Buffer` in browser, we test for `atob` and if it's there, use `Uint8Array`: https://github.com/dchest/tweetnacl-util-js/blob/master/nacl-util.js#L35-L38

**Comment by kumavis** [comment]
I see, my mistake

I was running a browserify bundle in node.js (for testing) and it did not have `atob` and `Buffer` was `undefined` so `Buffer.from` threw
